###### A DataFrame in pandas is a 2-dimensional table-like data structure used to store and work with data in rows and columns.

In [ ]:
import numpy as np
import pandas as pd

# Creating a Dataframe

In [15]:
data = {
    'Name' : ['John','Anna','Peter','Linda'],
    'Age'  : [20,34,29,42],
    'City' : ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000,70000,62000,85000]
}

df=pd.DataFrame(data)

In [16]:
df

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# Using list

data_list=[
    ['John',20,'New York',65000],
    ['Anna',34,'Paris',62000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]

col=['Name','Age','City','Salary']
df2=pd.DataFrame(data_list,columns=col)

In [13]:
df2

    Name  Age      City  Salary
0   John   20  New York   65000
1   Anna   34     Paris   62000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Selecting and indexing the Columns

In [18]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [20]:
df[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [ ]:
df.columns # To check all the columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

##### Creating a new Column

In [24]:
df["Designation"] = ['Doctor','Teacher','Politician','Coder']

In [25]:
df

    Name  Age      City  Salary Desgignation Designation
0   John   20  New York   65000       Doctor      Doctor
1   Anna   34     Paris   70000      Teacher     Teacher
2  Peter   29    Berlin   62000   Politician  Politician
3  Linda   42    London   85000        Coder       Coder

##### Removing a Column

In [27]:
df.drop('Desgignation',axis=1)

    Name  Age      City  Salary Designation
0   John   20  New York   65000      Doctor
1   Anna   34     Paris   70000     Teacher
2  Peter   29    Berlin   62000  Politician
3  Linda   42    London   85000       Coder

In [ ]:
df # by droping the column still columns shows
# To delete permanantely columns use inplace=True

    Name  Age      City  Salary Desgignation Designation
0   John   20  New York   65000       Doctor      Doctor
1   Anna   34     Paris   70000      Teacher     Teacher
2  Peter   29    Berlin   62000   Politician  Politician
3  Linda   42    London   85000        Coder       Coder

In [ ]:
df.drop('Desgignation',axis=1,inplace=True)
df.drop(0,axis=0) # Removing rows

In [30]:
df

    Name  Age      City  Salary Designation
0   John   20  New York   65000      Doctor
1   Anna   34     Paris   70000     Teacher
2  Peter   29    Berlin   62000  Politician
3  Linda   42    London   85000       Coder

##### Selecting Rows

In [ ]:
# Using LOC to select a rows
df.loc[0]
df.loc[[0,1]] # Multiple rows selecting

   Name  Age      City  Salary Designation
0  John   20  New York   65000      Doctor
1  Anna   34     Paris   70000     Teacher

##### Selecting Subsets of Rows and Columns

In [33]:
df.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   20  New York   65000      Doctor
1  Anna   34     Paris   70000     Teacher

In [35]:
df.loc[[0,1]][['City','Salary','Designation']]

       City  Salary Designation
0  New York   65000      Doctor
1     Paris   70000     Teacher

In [36]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

##### Conditional Selection

In [42]:
df[df['Salary']>=70000]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000     Teacher
3  Linda   42  London   85000       Coder

In [47]:
# Select the people whose age is above 30 and their city must be paris

df[(df['Age']>30) & (df['City']=='Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000     Teacher

In [64]:
df.iloc[0:3,1:5]

   Age      City  Salary Designation
0   20  New York   65000      Doctor
1   34     Paris   70000     Teacher
2   29    Berlin   62000  Politician

In [65]:
df.head

<bound method NDFrame.head of     Name  Age      City  Salary Designation
0   John   20  New York   65000      Doctor
1   Anna   34     Paris   70000     Teacher
2  Peter   29    Berlin   62000  Politician
3  Linda   42    London   85000       Coder>

In [66]:
df.tail

<bound method NDFrame.tail of     Name  Age      City  Salary Designation
0   John   20  New York   65000      Doctor
1   Anna   34     Paris   70000     Teacher
2  Peter   29    Berlin   62000  Politician
3  Linda   42    London   85000       Coder>

In [71]:
df.head(2)

   Name  Age      City  Salary Designation
0  John   20  New York   65000      Doctor
1  Anna   34     Paris   70000     Teacher