##### Finding Missing Value

In [2]:
import numpy as np
import pandas as pd

In [19]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5],
}
df = pd.DataFrame(data)

In [20]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [21]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [22]:
df.isna().sum() # Total null value in every rows

A    1
B    0
C    2
D    3
dtype: int64

In [23]:
df.isna().any() # Is there any column where null value not

A     True
B    False
C     True
D     True
dtype: bool

##### Removing Missong Data

In [29]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [24]:
df.dropna() # It will remove null value rows

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3) # drop rows where at least thresh value non-null value present

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

##### Filling Null Value

In [33]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [35]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [39]:
# Using customize value:
val={'A':0,'C':15,'D':20} # Filling value will be columns wise
df.fillna(val)

     A  B     C     D
0  1.0  1   1.0   1.0
1  2.0  2   2.0  20.0
2  0.0  3   3.0  20.0
3  4.0  4  15.0  20.0
4  5.0  5  15.0   5.0

In [40]:
# Filling value with mean
df.mean()

A    3.0
B    3.0
C    2.0
D    3.0
dtype: float64

In [41]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0