##### Group by

In [ ]:
# import numpy as np
import pandas as pd

In [6]:
data = {

    'Category' : ['A','B','A','B','A','B','A','B'],
    'Store'    : ['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Sales'    : [100,200,150,250,120,180,200,300],
    'Quantity' : [10,15,12,18,8,20,15,25],
    'Date'     : pd.date_range('2026-01-01',periods=8)

}
df=pd.DataFrame(data)

In [9]:
# Group by Category and calculate the sum of sales
df.groupby('Category') # it returns a object u cant print that 

cat=df.groupby('Category')

for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2026-01-01
2        A    S2    150        12 2026-01-03
4        A    S1    120         8 2026-01-05
6        A    S2    200        15 2026-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2026-01-02
3        B    S2    250        18 2026-01-04
5        B    S2    180        20 2026-01-06
7        B    S1    300        25 2026-01-08

In [13]:
cat=df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [15]:
# Group by Store and calculate the sum of sales

st=df.groupby('Store')['Sales'].sum()
st

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [17]:
# Group by multiple columns 
# Group by Category and store 

st=df.groupby(['Category','Store'])['Sales'].sum()
st

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

#### Aggregation

In [23]:
print(df['Sales'].mean())

187.5

In [29]:
print(df['Sales'].median())
print(df['Sales'].std())
print(df['Sales'].var())
print(df['Sales'].min())
print(df['Sales'].max())

190.0
66.06274074155351
4364.285714285715
100
300

Aggregation keyword

In [31]:
df['Sales'].agg(['mean','median','std','var','max','min','count'])

mean       187.500000
median     190.000000
std         66.062741
var       4364.285714
max        300.000000
min        100.000000
count        8.000000
Name: Sales, dtype: float64

#### Mode in not count as aggreagate function because all other function returns only one value but mode return more than one value it counts frequency might be same

In [32]:
df.head()

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2026-01-01
1        B    S1    200        15 2026-01-02
2        A    S2    150        12 2026-01-03
3        B    S2    250        18 2026-01-04
4        A    S1    120         8 2026-01-05

In [33]:
df.tail()

  Category Store  Sales  Quantity       Date
3        B    S2    250        18 2026-01-04
4        A    S1    120         8 2026-01-05
5        B    S2    180        20 2026-01-06
6        A    S2    200        15 2026-01-07
7        B    S1    300        25 2026-01-08

In [35]:
df.shape

(8, 5)

In [37]:
df.count()

Category    8
Store       8
Sales       8
Quantity    8
Date        8
dtype: int64

In [49]:
df.loc[[0,2],['Sales']]

   Sales
0    100
2    150

In [54]:
df.iloc[0:2,2:3]

   Sales
0    100
1    200