In [90]:
import pandas as pd
import numpy as np

In [91]:
df=pd.DataFrame({
    'Name' : ['Anurag','Ansh','Rahul','Somiya','Negi'],
    'Marks' : [56,89,np.nan,41,99],
    'city' : ['Loni','Vaishali','Saket','Rohini','Dehradun'],
    'State' : ['Ghaziabad','Uttarpradesh','New Delhi', 'Uttarpradesh', 'Uttrakhand'],
    
})

### Viewing & inspecting Data

In [92]:
'''
head            => Show first n rows
df.tail(n)	    => Show last n rows
df.sample(n)	=> Random rows
df.shape	    => Number of rows & columns
df.columns	    => Column names
df.index	    => Row index
df.info()	    => Data types & missing values
df.describe()	=> Summary statistics
df.dtypes	    => Data types of columns

'''

'\nhead            => Show first n rows\ndf.tail(n)\t    => Show last n rows\ndf.sample(n)\t=> Random rows\ndf.shape\t    => Number of rows & columns\ndf.columns\t    => Column names\ndf.index\t    => Row index\ndf.info()\t    => Data types & missing values\ndf.describe()\t=> Summary statistics\ndf.dtypes\t    => Data types of columns\n\n'

In [93]:
df.head()

     Name  Marks      city         State
0  Anurag   56.0      Loni     Ghaziabad
1    Ansh   89.0  Vaishali  Uttarpradesh
2   Rahul    NaN     Saket     New Delhi
3  Somiya   41.0    Rohini  Uttarpradesh
4    Negi   99.0  Dehradun    Uttrakhand

In [94]:
df.tail(4)

     Name  Marks      city         State
1    Ansh   89.0  Vaishali  Uttarpradesh
2   Rahul    NaN     Saket     New Delhi
3  Somiya   41.0    Rohini  Uttarpradesh
4    Negi   99.0  Dehradun    Uttrakhand

In [95]:
df.shape

(5, 4)

In [96]:
df.columns

Index(['Name', 'Marks', 'city', 'State'], dtype='object')

In [97]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Marks   4 non-null      float64
 2   city    5 non-null      object
 3   State   5 non-null      object
dtypes: float64(1), object(3)
memory usage: 288.0+ bytes

In [99]:
df.describe()

           Marks
count   4.000000
mean   71.250000
std    27.280946
min    41.000000
25%    52.250000
50%    72.500000
75%    91.500000
max    99.000000

In [100]:
df.dtypes

Name      object
Marks    float64
city      object
State     object
dtype: object

### Selecting Data

In [101]:
'''
df['col']	        => Select column
df[['c1','c2']]	    => Multiple columns
df.loc[]	        => Label-based selection  last value include
df.iloc[]	        => Position-based selection last value exclude
df.at[]	            => Fast scalar access
df.iat[]	        => Fast integer position access

'''

"\ndf['col']\t        => Select column\ndf[['c1','c2']]\t    => Multiple columns\ndf.loc[]\t        => Label-based selection  last value include\ndf.iloc[]\t        => Position-based selection last value exclude\ndf.at[]\t            => Fast scalar access\ndf.iat[]\t        => Fast integer position access\n\n"

In [102]:
df['Name']

0    Anurag
1      Ansh
2     Rahul
3    Somiya
4      Negi
Name: Name, dtype: object

In [103]:
df[['Name','Marks']]

     Name  Marks
0  Anurag   56.0
1    Ansh   89.0
2   Rahul    NaN
3  Somiya   41.0
4    Negi   99.0

In [104]:
df.loc[0:3,['Marks']]

   Marks
0   56.0
1   89.0
2    NaN
3   41.0

In [105]:
df.iloc[0:2,1:3]

   Marks      city
0   56.0      Loni
1   89.0  Vaishali

In [106]:
df.at[1,'Marks'] # Label based

np.float64(89.0)

In [107]:
df.iat[2,3]   # row index and column index

'New Delhi'

In [108]:
df

     Name  Marks      city         State
0  Anurag   56.0      Loni     Ghaziabad
1    Ansh   89.0  Vaishali  Uttarpradesh
2   Rahul    NaN     Saket     New Delhi
3  Somiya   41.0    Rohini  Uttarpradesh
4    Negi   99.0  Dehradun    Uttrakhand

### Filtering Data

In [109]:
'''

isin()	    => Match values in list
between()	=> Range filtering
query()	    => SQL-like filtering

'''

'\n\nisin()\t    => Match values in list\nbetween()\t=> Range filtering\nquery()\t    => SQL-like filtering\n\n'

In [110]:
li=['New Delhi']
df['State'].isin(li)

0    False
1    False
2     True
3    False
4    False
Name: State, dtype: bool

In [111]:
df

     Name  Marks      city         State
0  Anurag   56.0      Loni     Ghaziabad
1    Ansh   89.0  Vaishali  Uttarpradesh
2   Rahul    NaN     Saket     New Delhi
3  Somiya   41.0    Rohini  Uttarpradesh
4    Negi   99.0  Dehradun    Uttrakhand

In [112]:
df['Marks'].between(20,50)

0    False
1    False
2    False
3     True
4    False
Name: Marks, dtype: bool

In [113]:
df.query("Marks>50 and State == 'New Delhi'")

Empty DataFrame
Columns: [Name, Marks, city, State]
Index: []

### Handaling Missing Data

In [114]:
'''
df.isnull()	        => Detect missing values
df.notnull()	    => Detect non-missing
df.dropna()	        => Remove missing rows
df.fillna()	        => Fill missing values
df.interpolate()	=> Estimate missing values
'''

'\ndf.isnull()\t        => Detect missing values\ndf.notnull()\t    => Detect non-missing\ndf.dropna()\t        => Remove missing rows\ndf.fillna()\t        => Fill missing values\ndf.interpolate()\t=> Estimate missing values\n'

In [115]:
df.isnull()

    Name  Marks   city  State
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3  False  False  False  False
4  False  False  False  False

In [116]:
df.notnull()

   Name  Marks  city  State
0  True   True  True   True
1  True   True  True   True
2  True  False  True   True
3  True   True  True   True
4  True   True  True   True

In [117]:
df.dropna()

     Name  Marks      city         State
0  Anurag   56.0      Loni     Ghaziabad
1    Ansh   89.0  Vaishali  Uttarpradesh
3  Somiya   41.0    Rohini  Uttarpradesh
4    Negi   99.0  Dehradun    Uttrakhand

In [118]:
df.fillna(56)

     Name  Marks      city         State
0  Anurag   56.0      Loni     Ghaziabad
1    Ansh   89.0  Vaishali  Uttarpradesh
2   Rahul   56.0     Saket     New Delhi
3  Somiya   41.0    Rohini  Uttarpradesh
4    Negi   99.0  Dehradun    Uttrakhand

In [119]:
df.interpolate()

C:\Users\hp\AppData\Local\Temp\ipykernel_20160\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

     Name  Marks      city         State
0  Anurag   56.0      Loni     Ghaziabad
1    Ansh   89.0  Vaishali  Uttarpradesh
2   Rahul   65.0     Saket     New Delhi
3  Somiya   41.0    Rohini  Uttarpradesh
4    Negi   99.0  Dehradun    Uttrakhand

In [120]:
df

     Name  Marks      city         State
0  Anurag   56.0      Loni     Ghaziabad
1    Ansh   89.0  Vaishali  Uttarpradesh
2   Rahul    NaN     Saket     New Delhi
3  Somiya   41.0    Rohini  Uttarpradesh
4    Negi   99.0  Dehradun    Uttrakhand

### Sorting Data

In [ ]:

'''
df.groupby()	 => Group rows
agg()	         => Apply multiple aggregations
transform()	     => Transform grouped data making a new column


'''

In [123]:
df.sort_values('Name',ascending=False)

     Name  Marks      city         State
3  Somiya   41.0    Rohini  Uttarpradesh
2   Rahul    NaN     Saket     New Delhi
4    Negi   99.0  Dehradun    Uttrakhand
0  Anurag   56.0      Loni     Ghaziabad
1    Ansh   89.0  Vaishali  Uttarpradesh

In [124]:
df.sort_index(ascending=False)

     Name  Marks      city         State
4    Negi   99.0  Dehradun    Uttrakhand
3  Somiya   41.0    Rohini  Uttarpradesh
2   Rahul    NaN     Saket     New Delhi
1    Ansh   89.0  Vaishali  Uttarpradesh
0  Anurag   56.0      Loni     Ghaziabad

### Grouping Data

In [184]:

df1 = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR", "Sales","Sales"],
    "Employee": ["A", "B", "C", "D", "E","E"],
    "Salary": [50000, 40000, 60000, 45000, 55000,55000]
})

In [186]:
df1

  Department Employee  Salary
0         IT        A   50000
1         HR        B   40000
2         IT        C   60000
3         HR        D   45000
4      Sales        E   55000
5      Sales        E   55000

In [187]:
df1.groupby('Department')['Salary'].max()

Department
HR       45000
IT       60000
Sales    55000
Name: Salary, dtype: int64

In [188]:
df1.groupby('Department')['Salary'].agg(['max','mean'])

              max     mean
Department
HR          45000  42500.0
IT          60000  55000.0
Sales       55000  55000.0

In [189]:
df1['Difference'] = df1['Salary'] - df1.groupby('Department')['Salary'].transform('mean')

In [190]:
df1

  Department Employee  Salary  Difference
0         IT        A   50000     -5000.0
1         HR        B   40000     -2500.0
2         IT        C   60000      5000.0
3         HR        D   45000      2500.0
4      Sales        E   55000         0.0
5      Sales        E   55000         0.0

### Modifying Data

In [ ]:
'''
df.rename()	   => Rename columns
df.drop()	   => Remove column/row
df.insert()	   => Insert column
df.assign()	   => Create new column
df.replace()   => Replace values

'''

In [191]:
df1.rename(columns={'Salary':'Wages'})

  Department Employee  Wages  Difference
0         IT        A  50000     -5000.0
1         HR        B  40000     -2500.0
2         IT        C  60000      5000.0
3         HR        D  45000      2500.0
4      Sales        E  55000         0.0
5      Sales        E  55000         0.0

In [192]:
df1.drop(columns='Difference')

  Department Employee  Salary
0         IT        A   50000
1         HR        B   40000
2         IT        C   60000
3         HR        D   45000
4      Sales        E   55000
5      Sales        E   55000

In [193]:
df1.insert(4,'Bonus',[5000,4000,6000,1000,2000,2000])

In [159]:
df1

  Department Employee  Salary  Difference  Bonus
0         IT        A   50000     -5000.0   5000
1         HR        B   40000     -2500.0   4000
2         IT        C   60000      5000.0   6000
3         HR        D   45000      2500.0   1000
4      Sales        E   55000         0.0   2000

In [194]:
df1.assign(Test='A')

  Department Employee  Salary  Difference  Bonus Test
0         IT        A   50000     -5000.0   5000    A
1         HR        B   40000     -2500.0   4000    A
2         IT        C   60000      5000.0   6000    A
3         HR        D   45000      2500.0   1000    A
4      Sales        E   55000         0.0   2000    A
5      Sales        E   55000         0.0   2000    A

In [195]:
df1.replace('HR','VR')

  Department Employee  Salary  Difference  Bonus
0         IT        A   50000     -5000.0   5000
1         VR        B   40000     -2500.0   4000
2         IT        C   60000      5000.0   6000
3         VR        D   45000      2500.0   1000
4      Sales        E   55000         0.0   2000
5      Sales        E   55000         0.0   2000

### Combining Data Frames

In [ ]:
'''

pd.concat()  	=> Combine vertically/horizontally
df.merge()	    => SQL-like join
df.join()	    => Join DataFrames

'''

### Remvoing Duplicates

In [196]:
df1

  Department Employee  Salary  Difference  Bonus
0         IT        A   50000     -5000.0   5000
1         HR        B   40000     -2500.0   4000
2         IT        C   60000      5000.0   6000
3         HR        D   45000      2500.0   1000
4      Sales        E   55000         0.0   2000
5      Sales        E   55000         0.0   2000

In [197]:
df1.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [199]:
df1.drop_duplicates()

  Department Employee  Salary  Difference  Bonus
0         IT        A   50000     -5000.0   5000
1         HR        B   40000     -2500.0   4000
2         IT        C   60000      5000.0   6000
3         HR        D   45000      2500.0   1000
4      Sales        E   55000         0.0   2000

### Value Analysis

In [ ]:
'''
df.value_counts()	 => Frequency counts
df.unique()	         => Unique values
df.nunique()	     => Number of unique values

'''

In [208]:
df1['Department'].value_counts()

Department
IT       2
HR       2
Sales    2
Name: count, dtype: int64

In [202]:
df1['Department'].count()

np.int64(6)

In [212]:
df1["Department"].unique()

array(['IT', 'HR', 'Sales'], dtype=object)

In [210]:
df1['Department'].nunique()
# df1['Department'].value_counts().count()

3

### Apply Custom Funtions

In [ ]:
''' 
df.apply()	     => Apply function column/row wise  Series or Dataframe
df.map()	     => Apply function to series        Series(single Column)
df.applymap()  	 => Apply function element-wise     iterates every single element of dataframe

'''

In [217]:
df1

  Department Employee  Salary  Difference  Bonus
0         IT        A   50000     -5000.0   5000
1         HR        B   40000     -2500.0   4000
2         IT        C   60000      5000.0   6000
3         HR        D   45000      2500.0   1000
4      Sales        E   55000         0.0   2000
5      Sales        E   55000         0.0   2000

In [220]:
df1['Bonus'].apply(lambda x : x*0.28)

0    1400.0
1    1120.0
2    1680.0
3     280.0
4     560.0
5     560.0
Name: Bonus, dtype: float64

In [221]:
df1['Bonus'].map(lambda x : x*0.28)

0    1400.0
1    1120.0
2    1680.0
3     280.0
4     560.0
5     560.0
Name: Bonus, dtype: float64

In [ ]:
ab = df1.applymap(lambda x : x/1000) # It apply in every single elemet of data frame if and only all values are int

### Export/Import

In [ ]:
'''

pd.read_csv()	      => Load CSV
df.to_csv()	          => Save CSV
pd.read_excel()	      => Load Excel
df.to_excel()	      => Save Excel
df.to_json()	      => Save JSON


'''