## Numpy Practice Set

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('employee.csv')

In [8]:
df.sample(5)

,emp_id,name,age,salary,exp,city,dept,performance_rating
30,31,Neeraj Sharma,28.0,NaN,3.0,Delhi,IT,4.0
97,98,Arpit Sharma,29.0,48000.0,4.0,Delhi,IT,4.0
0,1,Rahul Sharma,28.0,45000.0,3.0,Delhi,IT,4.0
41,42,Ananya Singh,31.0,57000.0,7.0,Lucknow,Finance,4.0
39,40,Pallavi Gupta,30.0,NaN,6.0,Delhi,HR,4.0

In [12]:
df.describe

<bound method NDFrame.describe of     emp_id          name   age   salary   exp       city        dept  \
0        1  Rahul Sharma  28.0  45000.0   3.0      Delhi          IT
1        2   Priya Singh   NaN  60000.0   7.0     Mumbai          HR
2        3    Amit Kumar  25.0      NaN   2.0  Bangalore          IT
3        4    Neha Gupta  30.0  52000.0   NaN       Pune     Finance
4        5   Arjun Verma  35.0  75000.0  10.0  Hyderabad       Sales
..     ...           ...   ...      ...   ...        ...         ...
95      96   Ayush Gupta  25.0  35000.0   2.0     Kanpur          IT
96      97     Neha Iyer  33.0  65000.0   8.0      Kochi     Finance
97      98  Arpit Sharma  29.0  48000.0   4.0      Delhi          IT
98      99     Riya Shah  25.0  36000.0   2.0     Mumbai          HR
99     100     Jay Mehta  37.0  81000.0  13.0  Ahmedabad  Management

    performance_rating
0                  4.0
1                  5.0
2                  3.0
3                  4.0
4                  NaN
..                 ...
95                 NaN
96                 4.0
97                 4.0
98                 3.0
99                 5.0

[100 rows x 8 columns]>

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   emp_id              100 non-null    int64
 1   name                97 non-null     object
 2   age                 87 non-null     float64
 3   salary              83 non-null     float64
 4   exp                 89 non-null     float64
 5   city                97 non-null     object
 6   dept                97 non-null     object
 7   performance_rating  85 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 6.4+ KB

In [22]:
# Checking the Missing Value

df.isnull().sum()

emp_id                 0
name                   3
age                   13
salary                17
exp                   11
city                   3
dept                   3
performance_rating    15
dtype: int64

In [33]:
# Filling missing Value in Salary

df['salary']=df['salary'].fillna(df['salary'].mean())

In [50]:
df.isnull().sum()

emp_id                 0
name                   3
age                   13
salary                 0
exp                   11
city                   3
dept                   3
performance_rating    15
dtype: int64

In [54]:
# df.drop_duplicates()
df.dropna(thresh=3)
df.isnull().sum()

emp_id                 0
name                   3
age                   13
salary                 0
exp                   11
city                   3
dept                   3
performance_rating    15
dtype: int64

In [56]:
df['performance_rating']=df['performance_rating'].fillna(df['performance_rating'].median())

In [57]:
df.isnull().sum()

emp_id                 0
name                   3
age                   13
salary                 0
exp                   11
city                   3
dept                   3
performance_rating     0
dtype: int64

In [69]:
df['age']=df['age'].fillna(df['age'].median()).round().astype(int)
df['exp']=df['exp'].fillna(df['exp'].mean()).round().astype(int)

In [70]:
df.head()

,emp_id,name,age,salary,exp,city,dept,performance_rating
0,1,Rahul Sharma,28,45000.0,3,Delhi,IT,4.0
1,2,Priya Singh,30,60000.0,7,Mumbai,HR,5.0
2,3,Amit Kumar,25,56590.0,2,Bangalore,IT,3.0
3,4,Neha Gupta,30,52000.0,6,Pune,Finance,4.0
4,5,Arjun Verma,35,75000.0,10,Hyderabad,Sales,4.0

In [71]:
df.isnull().sum()

emp_id                0
name                  3
age                   0
salary                0
exp                   0
city                  3
dept                  3
performance_rating    0
dtype: int64

In [72]:
df['name'] = df['name'].fillna('Unknown')

In [73]:
df['city'] =df['city'].fillna(df['city'].mode()[0])

In [74]:
df['dept'] =df['dept'].fillna(df['dept'].mode()[0])

In [75]:
df.isnull().sum()

emp_id                0
name                  0
age                   0
salary                0
exp                   0
city                  0
dept                  0
performance_rating    0
dtype: int64

In [76]:
df.head()

,emp_id,name,age,salary,exp,city,dept,performance_rating
0,1,Rahul Sharma,28,45000.0,3,Delhi,IT,4.0
1,2,Priya Singh,30,60000.0,7,Mumbai,HR,5.0
2,3,Amit Kumar,25,56590.0,2,Bangalore,IT,3.0
3,4,Neha Gupta,30,52000.0,6,Pune,Finance,4.0
4,5,Arjun Verma,35,75000.0,10,Hyderabad,Sales,4.0

In [77]:
df

,emp_id,name,age,salary,exp,city,dept,performance_rating
0,1,Rahul Sharma,28,45000.0,3,Delhi,IT,4.0
1,2,Priya Singh,30,60000.0,7,Mumbai,HR,5.0
2,3,Amit Kumar,25,56590.0,2,Bangalore,IT,3.0
3,4,Neha Gupta,30,52000.0,6,Pune,Finance,4.0
4,5,Arjun Verma,35,75000.0,10,Hyderabad,Sales,4.0
...,...,...,...,...,...,...,...,...
95,96,Ayush Gupta,25,35000.0,2,Kanpur,IT,4.0
96,97,Neha Iyer,33,65000.0,8,Kochi,Finance,4.0
97,98,Arpit Sharma,29,48000.0,4,Delhi,IT,4.0
98,99,Riya Shah,25,36000.0,2,Mumbai,HR,3.0
99,100,Jay Mehta,37,81000.0,13,Ahmedabad,Management,5.0

In [ ]:
df.to_csv('Cleaned_employee.csv',index=False) #We use index=False in to_csv() to prevent pandas from saving the DataFrame index as a separate column in the CSV file.